"""add external recipe fields + snapshot

Revision ID: d5bd84a98b7e
Revises: 9227e7c85708
Create Date: 2025-09-18 19:55:41.342498

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5bd84a98b7e'
down_revision = '9227e7c85708'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('external_recipes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('external_id', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('image', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'external_id')
    )
    with op.batch_alter_table('meal_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('external_provider', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('external_id', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('external_title', sa.String(length=300), nullable=True))
        batch_op.add_column(sa.Column('external_image', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('ingredient_snapshot', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meal_items', schema=None) as batch_op:
        batch_op.drop_column('ingredient_snapshot')
        batch_op.drop_column('external_image')
        batch_op.drop_column('external_title')
        batch_op.drop_column('external_id')
        batch_op.drop_column('external_provider')

    op.drop_table('external_recipes')
    # ### end Alembic commands ###
